services:
  - type: web
    name: covered-call-calc
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run covered_call_calc.py --server.port=$PORT --server.enableCORS=false
    repo: https://github.com/michaelsaeed/online_calculator
    branch: main  # or your actual branch name
    autoDeploy: true
